name: CI

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'
  workflow_dispatch:

jobs:
  compile-sketches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: esp32:esp32:esp32s3
          platforms: |
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          libraries: |
            - source-url: https://github.com/micro-ROS/micro_ros_arduino/archive/refs/tags/v2.0.5-humble.zip
          cli-compile-flags: |
            - --build-property
            - compiler.cpp.extra_flags=-Wno-error=unused-but-set-parameter -Wno-error=unused-but-set-variable -Wno-error=unused-variable  -Wno-error=switch -Wno-error=char-subscripts -Wno-error=return-type
          sketch-paths: |
            - uROS_STEP1_LED
            - uROS_STEP2_SWITCH
            - uROS_STEP3_Buzzer
            - uROS_STEP4_Sensor
            - uROS_STEP5_Straight
            - uROS_STEP6_rotate
            - uROS_STEP7_P_control
            - uROS_STEP8_micromouse
            - uROS_STEP10_twistMsg

