name: CI

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'
  workflow_dispatch:

jobs:
  compile-sketches:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - uses: arduino/compile-sketches@v1
      with:
        # 要修正
        fqbn: arduino:avr:uno
        sketch-paths: |
          - uROS_STEP1_LED
